name: deploy_to_dev
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to DEV server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEV_PK }}
          REMOTE_HOST: ${{ secrets.DEV_HOST }}
          REMOTE_USER: ${{ secrets.DEV_USER }}
          REMOTE_PORT: ${{ secrets.DEV_PORT }}
          SOURCE: ./*
          TARGET: /home/cicd/tmp/pennoe_payment-client

      - name: Restart service
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          privateKey: ${{ secrets.DEV_PK }}
          port: ${{ secrets.DEV_PORT }}
          command: |
            rm -rf /home/cicd/projects/pennoe_payment-client
            mkdir -p /home/cicd/projects/pennoe_payment-client
            cp -r /home/cicd/tmp/pennoe_payment-client /home/cicd/projects/
            rm -rf /home/cicd/tmp/pennoe_payment-client
            cd /home/cicd/projects/pennoe_payment-client/ && npm i && npx nuxi build
            sudo systemctl restart pennoe_payment-client.service
